### PR TITLE
SECURITY - Github

### PR DESCRIPTION
**Pull request by SynovialWheat9011**
Faites intervenir Stackblitz.

### CODE REVIEW

**Comment by SynovialWheat9011** [comment]
medikoo a ajouté des commits.

**Comment by SynovialWheat9011** [comment]
medikoo a ajouté des commits.

**Comment by greysteil** [comment]
Thanks, but this appears to be a generic template.

**Comment by SynovialWheat9011** [comment]
Hi !

**Comment by SynovialWheat9011** [comment]
Hi !

**Pull request closed without merging**
